language: generic
sudo: required
dist: trusty


matrix:
  fast_finish: true

  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'cmake', 'realpath', 'libbz2-dev', 'zlib1g-dev', 'libexpat1-dev', 'libboost-all-dev']
      env: CCOMPILER='gcc-7' CXXCOMPILER='g++-7'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cmake', 'realpath', 'libbz2-dev', 'zlib1g-dev', 'libexpat1-dev', 'libboost-all-dev']
      env: CCOMPILER='gcc-6' CXXCOMPILER='g++-6'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake', 'realpath', 'libbz2-dev', 'zlib1g-dev', 'libexpat1-dev', 'libboost-all-dev']
      env: CCOMPILER='gcc-5' CXXCOMPILER='g++-5'

    # Waiting on Travis whitelisting clang-4.0


before_install:
  - export CC=${CCOMPILER} CXX=${CXXCOMPILER}

install:
  - ./deps.sh
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - popd
  # In addition test the mason build
  - rm -rf build third_party
  - ./masonize.sh
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_MASON=On
  - cmake --build .
  - popd

script:
  - pushd tests
  - ./check.sh
